/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package E142;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class E142 extends javax.swing.JFrame {

    /**
     * Creates new form E142
     */
    public E142() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jItalia = new javax.swing.JCheckBox();
        jIrlanda = new javax.swing.JCheckBox();
        jSpain = new javax.swing.JCheckBox();
        jPortugal = new javax.swing.JCheckBox();
        jListaPaises = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        jItalia.setText("Italia");
        jItalia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItaliaActionPerformed(evt);
            }
        });

        jIrlanda.setText("Irlanda");
        jIrlanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIrlandaActionPerformed(evt);
            }
        });

        jSpain.setText("España");
        jSpain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSpainActionPerformed(evt);
            }
        });

        jPortugal.setText("Portugal");
        jPortugal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPortugalActionPerformed(evt);
            }
        });

        jListaPaises.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jListaPaisesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jIrlanda)
                            .addComponent(jPortugal)
                            .addComponent(jItalia))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSpain)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(218, Short.MAX_VALUE)
                .addComponent(jListaPaises, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jListaPaises, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSpain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jItalia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jIrlanda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPortugal)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jSpainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSpainActionPerformed
        // TODO add your handling code here:
        if(jSpain.isSelected()){
            jListaPaises.addItem(jSpain.getText());
        }else{
            jListaPaises.removeItem(jSpain.getText());
        }
    }//GEN-LAST:event_jSpainActionPerformed

    private void jListaPaisesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jListaPaisesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jListaPaisesActionPerformed

    private void jItaliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItaliaActionPerformed
        // TODO add your handling code here:
         if(jItalia.isSelected()){
            jListaPaises.addItem(jItalia.getText());
        }else{
            jListaPaises.removeItem(jItalia.getText());
        }
    }//GEN-LAST:event_jItaliaActionPerformed

    private void jIrlandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIrlandaActionPerformed
        // TODO add your handling code here:
         if(jIrlanda.isSelected()){
            jListaPaises.addItem(jIrlanda.getText());
        }else{
            jListaPaises.removeItem(jIrlanda.getText());
        }
    }//GEN-LAST:event_jIrlandaActionPerformed

    private void jPortugalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPortugalActionPerformed
        // TODO add your handling code here:
        if(jPortugal.isSelected()){
            jListaPaises.addItem(jPortugal.getText());
        }else{
            jListaPaises.removeItem(jPortugal.getText());
        }
    }//GEN-LAST:event_jPortugalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(E142.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(E142.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(E142.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(E142.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new E142().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jIrlanda;
    private javax.swing.JCheckBox jItalia;
    private javax.swing.JComboBox<String> jListaPaises;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox jPortugal;
    private javax.swing.JCheckBox jSpain;
    // End of variables declaration//GEN-END:variables
}
