/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package E144;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class E144 extends javax.swing.JFrame {

    /**
     * Creates new form E144
     */
    public E144() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBoton3 = new javax.swing.JButton();
        jBoton5 = new javax.swing.JButton();
        jBoton6 = new javax.swing.JButton();
        jBoton7 = new javax.swing.JButton();
        jBoton4 = new javax.swing.JButton();
        jBoton2 = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();
        jBoton8 = new javax.swing.JButton();
        jBoton9 = new javax.swing.JButton();
        jBoton0 = new javax.swing.JButton();
        jBotonSumar = new javax.swing.JButton();
        jBotonRestar = new javax.swing.JButton();
        jBotonMultiplicar = new javax.swing.JButton();
        jBoton1 = new javax.swing.JButton();
        jBotonDividir = new javax.swing.JButton();
        jBotonResultado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBoton3.setText("3");
        getContentPane().add(jBoton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 40, 30));

        jBoton5.setText("5");
        getContentPane().add(jBoton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 40, 30));

        jBoton6.setText("6");
        getContentPane().add(jBoton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 40, 30));

        jBoton7.setText("7");
        getContentPane().add(jBoton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 40, 30));

        jBoton4.setText("4");
        getContentPane().add(jBoton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 40, 30));

        jBoton2.setText("2");
        getContentPane().add(jBoton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 40, 30));

        Limpiar.setText("C");
        getContentPane().add(Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 130, 30));

        jBoton8.setText("8");
        getContentPane().add(jBoton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 40, 30));

        jBoton9.setText("9");
        getContentPane().add(jBoton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 40, 30));

        jBoton0.setText("0");
        jBoton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoton0ActionPerformed(evt);
            }
        });
        getContentPane().add(jBoton0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 40, 30));

        jBotonSumar.setText("+");
        getContentPane().add(jBotonSumar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 40, 30));

        jBotonRestar.setText("-");
        getContentPane().add(jBotonRestar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 40, 30));

        jBotonMultiplicar.setText("*");
        getContentPane().add(jBotonMultiplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 40, 30));

        jBoton1.setText("1");
        getContentPane().add(jBoton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 40, 30));

        jBotonDividir.setText("/");
        getContentPane().add(jBotonDividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 40, 30));

        jBotonResultado.setText("=");
        getContentPane().add(jBotonResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 40, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBoton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoton0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBoton0ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(E144.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(E144.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(E144.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(E144.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new E144().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Limpiar;
    private javax.swing.JButton jBoton0;
    private javax.swing.JButton jBoton1;
    private javax.swing.JButton jBoton2;
    private javax.swing.JButton jBoton3;
    private javax.swing.JButton jBoton4;
    private javax.swing.JButton jBoton5;
    private javax.swing.JButton jBoton6;
    private javax.swing.JButton jBoton7;
    private javax.swing.JButton jBoton8;
    private javax.swing.JButton jBoton9;
    private javax.swing.JButton jBotonDividir;
    private javax.swing.JButton jBotonMultiplicar;
    private javax.swing.JButton jBotonRestar;
    private javax.swing.JButton jBotonResultado;
    private javax.swing.JButton jBotonSumar;
    // End of variables declaration//GEN-END:variables
}
