/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package E140;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class E140 extends javax.swing.JFrame {

    /**
     * Creates new form E140
     */
    public E140() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        jEntradaDolares = new javax.swing.JTextField();
        jSalidaEuros = new javax.swing.JTextField();
        jBotonDolarAEuro = new javax.swing.JButton();
        jSalidaDolares = new javax.swing.JTextField();
        jEntradaEuros = new javax.swing.JTextField();
        jBotonEuroADolar = new javax.swing.JButton();
        jEntradaDinero = new javax.swing.JTextField();
        jSalidaDinero = new javax.swing.JTextField();
        jListaConversion = new javax.swing.JComboBox<>();
        bBotonConvertir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanelFondo.setBackground(new java.awt.Color(153, 255, 153));

        jSalidaEuros.setEditable(false);

        jBotonDolarAEuro.setText("$ -> €");
        jBotonDolarAEuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonDolarAEuroActionPerformed(evt);
            }
        });

        jBotonEuroADolar.setText("€ -> $");
        jBotonEuroADolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonEuroADolarActionPerformed(evt);
            }
        });

        jSalidaDinero.setEditable(false);

        jListaConversion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "€ -> $", "$ -> €" }));

        bBotonConvertir.setText("Convertir");
        bBotonConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBotonConvertirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFondoLayout = new javax.swing.GroupLayout(jPanelFondo);
        jPanelFondo.setLayout(jPanelFondoLayout);
        jPanelFondoLayout.setHorizontalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFondoLayout.createSequentialGroup()
                        .addComponent(jEntradaDolares, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBotonDolarAEuro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelFondoLayout.createSequentialGroup()
                        .addComponent(jEntradaEuros, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBotonEuroADolar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelFondoLayout.createSequentialGroup()
                        .addComponent(jEntradaDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jListaConversion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bBotonConvertir, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSalidaDolares, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSalidaEuros, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSalidaDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );
        jPanelFondoLayout.setVerticalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jEntradaDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelFondoLayout.createSequentialGroup()
                        .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jEntradaDolares, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSalidaEuros, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBotonDolarAEuro, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSalidaDolares, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEntradaEuros, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBotonEuroADolar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSalidaDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelFondoLayout.createSequentialGroup()
                                .addComponent(bBotonConvertir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jListaConversion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBotonDolarAEuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonDolarAEuroActionPerformed
       try{
        double cantidadInsertada =Double.parseDouble(jEntradaDolares.getText());
        jSalidaEuros.setText(String.valueOf(cantidadInsertada*0.93));
       }catch(RuntimeException e){
           System.out.println("Error!: "+e.getMessage());
           jEntradaDolares.setText("");
       }
    }//GEN-LAST:event_jBotonDolarAEuroActionPerformed

    private void jBotonEuroADolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonEuroADolarActionPerformed
        // TODO add your handling code here:
         try{
        double cantidadInsertada =Double.parseDouble(jEntradaEuros.getText());
        jSalidaDolares.setText(String.valueOf(cantidadInsertada*1.075269));
       }catch(RuntimeException e){
           System.out.println("Error!: "+e.getMessage());
           jEntradaEuros.setText("");
       }
    }//GEN-LAST:event_jBotonEuroADolarActionPerformed

    private void bBotonConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBotonConvertirActionPerformed
        //Boton convertir.
        
        if( jListaConversion.getSelectedIndex()==0){//Caso 0 es caso de euro a dolar.
         try{
        double cantidadInsertada =Double.parseDouble(jEntradaDinero.getText());
        jSalidaDinero.setText(String.valueOf(cantidadInsertada*1.075269));
       }catch(RuntimeException e){
           System.out.println("Error!: "+e.getMessage());
           jEntradaDinero.setText("");
       }           
        }else{//Caso dolar a euro.
         try{
        double cantidadInsertada =Double.parseDouble(jEntradaDinero.getText());
        jSalidaDinero.setText(String.valueOf(cantidadInsertada*0.93));
       }catch(RuntimeException e){
           System.out.println("Error!: "+e.getMessage());
           jEntradaDinero.setText("");
       }     
            
        }
    }//GEN-LAST:event_bBotonConvertirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(E140.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(E140.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(E140.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(E140.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new E140().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBotonConvertir;
    private javax.swing.JButton jBotonDolarAEuro;
    private javax.swing.JButton jBotonEuroADolar;
    private javax.swing.JTextField jEntradaDinero;
    private javax.swing.JTextField jEntradaDolares;
    private javax.swing.JTextField jEntradaEuros;
    private javax.swing.JComboBox<String> jListaConversion;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JTextField jSalidaDinero;
    private javax.swing.JTextField jSalidaDolares;
    private javax.swing.JTextField jSalidaEuros;
    // End of variables declaration//GEN-END:variables
}
