/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package E141;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class E141 extends javax.swing.JFrame {

    /**
     * Creates new form E141
     */
    public E141() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgConversiones = new javax.swing.ButtonGroup();
        jPanelFondo = new javax.swing.JPanel();
        jTitulo = new javax.swing.JLabel();
        jEntradaGrados = new javax.swing.JTextField();
        jSalidaGrados = new javax.swing.JTextField();
        bCaF = new javax.swing.JRadioButton();
        bFaC = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanelFondo.setBackground(new java.awt.Color(153, 153, 255));

        jTitulo.setBackground(new java.awt.Color(51, 51, 255));
        jTitulo.setFont(new java.awt.Font("sansserif", 2, 18)); // NOI18N
        jTitulo.setForeground(new java.awt.Color(0, 0, 255));
        jTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTitulo.setText("Conversor de grados");

        jEntradaGrados.setText(" ");
        jEntradaGrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEntradaGradosActionPerformed(evt);
            }
        });

        bgConversiones.add(bCaF);
        bCaF.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        bCaF.setForeground(new java.awt.Color(0, 0, 0));
        bCaF.setText("ºC --> ºF");
        bCaF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCaFActionPerformed(evt);
            }
        });

        bgConversiones.add(bFaC);
        bFaC.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        bFaC.setForeground(new java.awt.Color(0, 0, 0));
        bFaC.setText("ºF --> ºC");

        jButton1.setText("Convertir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFondoLayout = new javax.swing.GroupLayout(jPanelFondo);
        jPanelFondo.setLayout(jPanelFondoLayout);
        jPanelFondoLayout.setHorizontalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFondoLayout.createSequentialGroup()
                        .addComponent(jTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFondoLayout.createSequentialGroup()
                        .addComponent(jEntradaGrados, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSalidaGrados, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFondoLayout.createSequentialGroup()
                        .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bFaC)
                            .addComponent(bCaF))
                        .addGap(161, 161, 161))))
        );
        jPanelFondoLayout.setVerticalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bCaF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bFaC)
                .addGap(18, 18, 18)
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jSalidaGrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEntradaGrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jEntradaGradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEntradaGradosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEntradaGradosActionPerformed

    private void bCaFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCaFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bCaFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Se pulsa el boton de convertir.
        //Primero comprobamos que boton del grupo esta seleccionado, para hacer una cosa, otra O ninguna
        bgConversiones.add(bCaF);
        bgConversiones.add(bFaC);
        if(bCaF.isSelected()){
           try{
               double gradosAConvertir = Double.parseDouble(jEntradaGrados.getText());
               jSalidaGrados.setText(String.valueOf(gradosAConvertir*1.8+32));
               
           }catch(RuntimeException e){
               System.out.println("Error: "+e.getMessage());
           }
        }else if(bFaC.isSelected()){
           try{
               double gradosAConvertir = Double.parseDouble(jEntradaGrados.getText());
               jSalidaGrados.setText(String.valueOf((gradosAConvertir-32)/1.8));
               
           }catch(RuntimeException e){
               
           }
            
        }
        
        

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(E141.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(E141.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(E141.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(E141.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new E141().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bCaF;
    private javax.swing.JRadioButton bFaC;
    private javax.swing.ButtonGroup bgConversiones;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jEntradaGrados;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JTextField jSalidaGrados;
    private javax.swing.JLabel jTitulo;
    // End of variables declaration//GEN-END:variables
}
