/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package E143;
import java.applet.AudioClip;

//Boolean para comprobar que el primer boton está correctamente seleccionado.

import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.LineUnavailableException;

public class E143 extends javax.swing.JFrame {
boolean fabricanteCorrecto=false, productoCorrecto=false;

    Clip clip = null;
    
    
  



    public E143() {
        initComponents();
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/E143/pokemonRojoWav.wav"));
        sonido.play();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        jListaFabricantes = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jListaProductos = new javax.swing.JComboBox<>();
        bValoresCorrectos = new javax.swing.JButton();
        bBotonMusica = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanelFondo.setBackground(new java.awt.Color(102, 255, 102));

        jListaFabricantes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una marca", "AMD", "Intel", "NVIDIA" }));
        jListaFabricantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jListaFabricantesActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tarjetas gráficas");

        jListaProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jListaProductosActionPerformed(evt);
            }
        });

        bValoresCorrectos.setText("Valores Correctos");
        bValoresCorrectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bValoresCorrectosActionPerformed(evt);
            }
        });

        bBotonMusica.setText("M");
        bBotonMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBotonMusicaActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFondoLayout = new javax.swing.GroupLayout(jPanelFondo);
        jPanelFondo.setLayout(jPanelFondoLayout);
        jPanelFondoLayout.setHorizontalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFondoLayout.createSequentialGroup()
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelFondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jListaFabricantes, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jListaProductos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelFondoLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(bValoresCorrectos, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(11, 11, 11)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(bBotonMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanelFondoLayout.setVerticalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFondoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1))
                    .addComponent(bBotonMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jListaFabricantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jListaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(bValoresCorrectos)
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jListaFabricantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jListaFabricantesActionPerformed
        // TODO add your handling code here:
        int indiceSeleccionado = jListaFabricantes.getSelectedIndex();
        switch (indiceSeleccionado){
            case 1:
                jListaProductos.removeAllItems();
                jListaProductos.addItem("Seleccione un modelo:");
                jListaProductos.addItem("RX Series 500");
                jListaProductos.addItem("Vega Series");
                jListaProductos.addItem("RX Series 6000");
                fabricanteCorrecto=true;
                break;
            case 2:
                jListaProductos.removeAllItems();
                jListaProductos.addItem("Seleccione un modelo:");
                jListaProductos.addItem("HD 3000");
                jListaProductos.addItem("HD 4000");
                jListaProductos.addItem("IRIS 600");
                fabricanteCorrecto=true;
                break;                
            case 3:
                jListaProductos.removeAllItems();
                jListaProductos.addItem("Seleccione un modelo:");
                jListaProductos.addItem("GTX Serie 1000");
                jListaProductos.addItem("GTX Serie 2000");
                jListaProductos.addItem("GTX Serie 3000");
                fabricanteCorrecto=true;
                break;
            default:
                jListaProductos.removeAllItems();
                fabricanteCorrecto=false;
                
               
        }
    }//GEN-LAST:event_jListaFabricantesActionPerformed

    private void jListaProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jListaProductosActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jListaProductosActionPerformed

    private void bValoresCorrectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bValoresCorrectosActionPerformed
        // TODO add your handling code here:
        int indiceSeleccionado = jListaProductos.getSelectedIndex();
        switch (indiceSeleccionado){
            case 1:
            case 2:
            case 3:
                productoCorrecto=true;
                break;
            default:
                productoCorrecto=false;
                
        }
        if((fabricanteCorrecto)&&(productoCorrecto)){
            JOptionPane.showMessageDialog(this, "Valores correctos.");
        }else{
            JOptionPane.showMessageDialog(this, "Valores erroneos.");    
        }
    }//GEN-LAST:event_bValoresCorrectosActionPerformed

    private void bBotonMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBotonMusicaActionPerformed
        // TODO add your handling code here:
        if(!bBotonMusica.isSelected()){
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/E143/pokemonRojoWav.wav"));
        sonido.play();
        }else{
      
        }
    }//GEN-LAST:event_bBotonMusicaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/E143/pokemonRojoWav.wav"));
        sonido.play();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(E143.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(E143.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(E143.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(E143.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new E143().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton bBotonMusica;
    private javax.swing.JButton bValoresCorrectos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> jListaFabricantes;
    private javax.swing.JComboBox<String> jListaProductos;
    private javax.swing.JPanel jPanelFondo;
    // End of variables declaration//GEN-END:variables
}
